#ifndef SEARCH_BY_REGION_GLOBAL_H
#define SEARCH_BY_REGION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SEARCH_BY_REGION_LIBRARY)
#  define SEARCH_BY_REGIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SEARCH_BY_REGIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SEARCH_BY_REGION_GLOBAL_H
