#ifndef LAYER_MANAGER_GLOBAL_H
#define LAYER_MANAGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LAYER_MANAGER_LIBRARY)
#  define LAYER_MANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LAYER_MANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LAYER_MANAGER_GLOBAL_H
